# Generated by Django 5.2.6 on 2025-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
                ('collection', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
